# coding: utf-8

"""
    Container Security API

    # Authentication You must authenticate to the Qualys Cloud Platform using Qualys account credentials (user name and password) and get the JSON Web Token (JWT) before you can start using the Container Security APIs. Use the Qualys Authentication API to get the JWT.  **Example Authentication Curl Request**:  curl -X POST https://gateway/auth -H 'Content-Type: application/x-www-form-urlencoded' -d 'username=value1&password=passwordValue&token=true' where - gateway is the base URL to the Qualys API server where your account is located. - **username** and **password** are the credentials of the user account for which you want to fetch Container Security data. - **token** should be **true** - **Content-Type** should be **application/x-www-form-urlencoded**   # noqa: E501

    OpenAPI spec version: v1.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.registry_api import RegistryApi  # noqa: E501
from swagger_client.rest import ApiException


class TestRegistryApi(unittest.TestCase):
    """RegistryApi unit test stubs"""

    def setUp(self):
        self.api = RegistryApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_cancel_cs_registry_schedule(self):
        """Test case for cancel_cs_registry_schedule

        Cancel registry schedule in your account.  # noqa: E501
        """
        pass

    def test_create_cs_acr_connector(self):
        """Test case for create_cs_acr_connector

        Create new ACR connector  # noqa: E501
        """
        pass

    def test_create_cs_aws_connector(self):
        """Test case for create_cs_aws_connector

        Create new AWS connector  # noqa: E501
        """
        pass

    def test_create_cs_gcp_connector(self):
        """Test case for create_cs_gcp_connector

        Create new GCP connector  # noqa: E501
        """
        pass

    def test_create_cs_registry(self):
        """Test case for create_cs_registry

        Create a new registry  # noqa: E501
        """
        pass

    def test_create_cs_registry_schedule(self):
        """Test case for create_cs_registry_schedule

        Create a new Registry scan schedule  # noqa: E501
        """
        pass

    def test_delete_cs_registries(self):
        """Test case for delete_cs_registries

        Delete multiple registries in your account  # noqa: E501
        """
        pass

    def test_delete_cs_registry(self):
        """Test case for delete_cs_registry

        Delete registry in you account  # noqa: E501
        """
        pass

    def test_delete_cs_registry_schedule(self):
        """Test case for delete_cs_registry_schedule

        Delete registry schedule in your account  # noqa: E501
        """
        pass

    def test_delete_cs_registry_schedules(self):
        """Test case for delete_cs_registry_schedules

        Delete multiple registry schedules in your account  # noqa: E501
        """
        pass

    def test_get_cs_acr_connectors_by_aws_account_id_using_get(self):
        """Test case for get_cs_acr_connectors_by_aws_account_id_using_get

        Show ACR connector details  # noqa: E501
        """
        pass

    def test_get_cs_acr_connectors_list_using_get(self):
        """Test case for get_cs_acr_connectors_list_using_get

        Show list of ACR connectors in your account  # noqa: E501
        """
        pass

    def test_get_cs_aws_account_id_using_get(self):
        """Test case for get_cs_aws_account_id_using_get

        Fetch AWS account ID and external ID for your account  # noqa: E501
        """
        pass

    def test_get_cs_aws_connectors_by_aws_account_id_using_get(self):
        """Test case for get_cs_aws_connectors_by_aws_account_id_using_get

        Show list of AWS connectors for an AWS account ID  # noqa: E501
        """
        pass

    def test_get_cs_aws_connectors_list_using_get(self):
        """Test case for get_cs_aws_connectors_list_using_get

        Show list of AWS connectors in your account  # noqa: E501
        """
        pass

    def test_get_cs_gcp_connectors_by_gcp_connector_id_using_get(self):
        """Test case for get_cs_gcp_connectors_by_gcp_connector_id_using_get

        Get GCP connector by connectorId  # noqa: E501
        """
        pass

    def test_get_cs_gcp_connectors_list_using_get(self):
        """Test case for get_cs_gcp_connectors_list_using_get

        Show list of GCP connectors in your account  # noqa: E501
        """
        pass

    def test_get_cs_registries_data_using_get(self):
        """Test case for get_cs_registries_data_using_get

        Show a list of registries in your account  # noqa: E501
        """
        pass

    def test_get_cs_registry_details(self):
        """Test case for get_cs_registry_details

        Show details of a registry  # noqa: E501
        """
        pass

    def test_get_cs_registry_repositories(self):
        """Test case for get_cs_registry_repositories

        Show a list of repositories in a registry  # noqa: E501
        """
        pass

    def test_get_cs_registry_schedules(self):
        """Test case for get_cs_registry_schedules

        Show a list of schedules created for a registry  # noqa: E501
        """
        pass

    def test_update_cs_registry(self):
        """Test case for update_cs_registry

        Update exiting registry in your account  # noqa: E501
        """
        pass

    def test_update_cs_registry_schedule(self):
        """Test case for update_cs_registry_schedule

        Update existing registry schedule in your account  # noqa: E501
        """
        pass

    def test_validate_cs_registry(self):
        """Test case for validate_cs_registry

        Validate information for new registry  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
