/*
 * Container Security API
 *
 * # Authentication You must authenticate to the Qualys Cloud Platform using Qualys account credentials (user name and password) and get the JSON Web Token (JWT) before you can start using the Container Security APIs. Use the Qualys Authentication API to get the JWT.  **Example Authentication Curl Request**:  curl -X POST https://gateway/auth -H 'Content-Type: application/x-www-form-urlencoded' -d 'username=value1&password=passwordValue&token=true' where - gateway is the base URL to the Qualys API server where your account is located. - **username** and **password** are the credentials of the user account for which you want to fetch Container Security data. - **token** should be **true** - **Content-Type** should be **application/x-www-form-urlencoded** 
 *
 * API version: v1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package qualys

type Registry struct {
	AwsAccountId string `json:"awsAccountId,omitempty"`
	AwsRegion string `json:"awsRegion,omitempty"`
	Created string `json:"created,omitempty"`
	DockerHubOrg string `json:"dockerHubOrg,omitempty"`
	LastScanned string `json:"lastScanned,omitempty"`
	ProviderType string `json:"providerType,omitempty"`
	RegistryType string `json:"registryType,omitempty"`
	RegistryUri string `json:"registryUri,omitempty"`
	RegistryUuid string `json:"registryUuid,omitempty"`
	RepoCount int32 `json:"repoCount,omitempty"`
	ScheduleStatusList *interface{} `json:"scheduleStatusList,omitempty"`
	TotalImages int32 `json:"totalImages,omitempty"`
	TotalScannedImages int32 `json:"totalScannedImages,omitempty"`
	TotalVulnerableImages int32 `json:"totalVulnerableImages,omitempty"`
	Updated string `json:"updated,omitempty"`
}
