/*
 * Container Security API
 *
 * # Authentication You must authenticate to the Qualys Cloud Platform using Qualys account credentials (user name and password) and get the JSON Web Token (JWT) before you can start using the Container Security APIs. Use the Qualys Authentication API to get the JWT.  **Example Authentication Curl Request**:  curl -X POST https://gateway/auth -H 'Content-Type: application/x-www-form-urlencoded' -d 'username=value1&password=passwordValue&token=true' where - gateway is the base URL to the Qualys API server where your account is located. - **username** and **password** are the credentials of the user account for which you want to fetch Container Security data. - **token** should be **true** - **Content-Type** should be **application/x-www-form-urlencoded** 
 *
 * API version: v1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package api

type Schedule struct {
	Created string `json:"created,omitempty"`
	Errors []ScheduleErrors `json:"errors,omitempty"`
	Filters []ScheduleFilters `json:"filters,omitempty"`
	JobCompletionDate string `json:"jobCompletionDate,omitempty"`
	JobListingCompletionDate string `json:"jobListingCompletionDate,omitempty"`
	JobListingStartDate string `json:"jobListingStartDate,omitempty"`
	JobScanningCompletionDate string `json:"jobScanningCompletionDate,omitempty"`
	JobScanningStartDate string `json:"jobScanningStartDate,omitempty"`
	JobStartDate string `json:"jobStartDate,omitempty"`
	Name string `json:"name,omitempty"`
	OnDemand bool `json:"onDemand,omitempty"`
	Schedule string `json:"schedule,omitempty"`
	ScheduleUuid string `json:"scheduleUuid,omitempty"`
	Status string `json:"status,omitempty"`
	Updated string `json:"updated,omitempty"`
}
