/*
 * Container Security API
 *
 * # Authentication You must authenticate to the Qualys Cloud Platform using Qualys account credentials (user name and password) and get the JSON Web Token (JWT) before you can start using the Container Security APIs. Use the Qualys Authentication API to get the JWT.  **Example Authentication Curl Request**:  curl -X POST https://gateway/auth -H 'Content-Type: application/x-www-form-urlencoded' -d 'username=value1&password=passwordValue&token=true' where - gateway is the base URL to the Qualys API server where your account is located. - **username** and **password** are the credentials of the user account for which you want to fetch Container Security data. - **token** should be **true** - **Content-Type** should be **application/x-www-form-urlencoded** 
 *
 * API version: v1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package qualys

type Sensor struct {
	ActivationUuid string `json:"activationUuid,omitempty"`
	BinaryVersion string `json:"binaryVersion,omitempty"`
	ConfigurationProfile string `json:"configurationProfile,omitempty"`
	ContainerIpv4 string `json:"containerIpv4,omitempty"`
	ContainerIpv6 string `json:"containerIpv6,omitempty"`
	ContainerMacAddress string `json:"containerMacAddress,omitempty"`
	Created string `json:"created,omitempty"`
	CustomerUuid string `json:"customerUuid,omitempty"`
	DockerVersion string `json:"dockerVersion,omitempty"`
	HostUuid string `json:"hostUuid,omitempty"`
	Hostname string `json:"hostname,omitempty"`
	ImageId string `json:"imageId,omitempty"`
	ImageSha string `json:"imageSha,omitempty"`
	Ipv4 string `json:"ipv4,omitempty"`
	Ipv6 string `json:"ipv6,omitempty"`
	Label *BulkContainerDetailsLabel `json:"label,omitempty"`
	LastCheckedIn string `json:"lastCheckedIn,omitempty"`
	MacAddress string `json:"macAddress,omitempty"`
	Name string `json:"name,omitempty"`
	Os string `json:"os,omitempty"`
	Platform string `json:"platform,omitempty"`
	Privileged string `json:"privileged,omitempty"`
	Registry string `json:"registry,omitempty"`
	SensorId string `json:"sensorId,omitempty"`
	SensorType string `json:"sensorType,omitempty"`
	SensorVersion string `json:"sensorVersion,omitempty"`
	Sha string `json:"sha,omitempty"`
	Status string `json:"status,omitempty"`
	Uuid string `json:"uuid,omitempty"`
	VulnSigVersion string `json:"vulnSigVersion,omitempty"`
	Cluster *Cluster `json:"cluster,omitempty"`
}
