/*
 * Container Security API
 *
 * # Authentication You must authenticate to the Qualys Cloud Platform using Qualys account credentials (user name and password) and get the JSON Web Token (JWT) before you can start using the Container Security APIs. Use the Qualys Authentication API to get the JWT.  **Example Authentication Curl Request**:  curl -X POST https://gateway/auth -H 'Content-Type: application/x-www-form-urlencoded' -d 'username=value1&password=passwordValue&token=true' where - gateway is the base URL to the Qualys API server where your account is located. - **username** and **password** are the credentials of the user account for which you want to fetch Container Security data. - **token** should be **true** - **Content-Type** should be **application/x-www-form-urlencoded** 
 *
 * API version: v1.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package api

type ContainerDetails struct {
	Arguments []string `json:"arguments,omitempty"`
	Command string `json:"command,omitempty"`
	ContainerId string `json:"containerId,omitempty"`
	Created string `json:"created,omitempty"`
	CustomerUuid string `json:"customerUuid,omitempty"`
	Drift *Drift `json:"drift,omitempty"`
	Environment []string `json:"environment,omitempty"`
	Host *Host `json:"host,omitempty"`
	Hostname string `json:"hostname,omitempty"`
	ImageId string `json:"imageId,omitempty"`
	ImageSha string `json:"imageSha,omitempty"`
	ImageUuid string `json:"imageUuid,omitempty"`
	Ipv4 string `json:"ipv4,omitempty"`
	Ipv6 string `json:"ipv6,omitempty"`
	IsDrift bool `json:"isDrift,omitempty"`
	IsInstrumented bool `json:"isInstrumented,omitempty"`
	IsRoot bool `json:"isRoot,omitempty"`
	Label []BulkContainerDetailsLabel `json:"label,omitempty"`
	LabelScanned string `json:"labelScanned,omitempty"`
	MacAddress string `json:"macAddress,omitempty"`
	Name string `json:"name,omitempty"`
	OperatingSystem string `json:"operatingSystem,omitempty"`
	Path string `json:"path,omitempty"`
	PortMapping []PortMapping `json:"portMapping,omitempty"`
	Privileged bool `json:"privileged,omitempty"`
	SensorUuid string `json:"sensorUuid,omitempty"`
	Services []ContainerDetailsServices `json:"services,omitempty"`
	Sha string `json:"sha,omitempty"`
	Softwares []ContainerDetailsSoftwares `json:"softwares,omitempty"`
	Source string `json:"source,omitempty"`
	State string `json:"state,omitempty"`
	StateChanged string `json:"stateChanged,omitempty"`
	Users []string `json:"users,omitempty"`
	Uuid string `json:"uuid,omitempty"`
	Vulnerabilities []Vulnerability `json:"vulnerabilities,omitempty"`
	Cluster *Cluster `json:"cluster,omitempty"`
}
