# coding: utf-8

"""
    Container Security API

    # Authentication You must authenticate to the Qualys Cloud Platform using Qualys account credentials (user name and password) and get the JSON Web Token (JWT) before you can start using the Container Security APIs. Use the Qualys Authentication API to get the JWT.  **Example Authentication Curl Request**:  curl -X POST https://gateway/auth -H 'Content-Type: application/x-www-form-urlencoded' -d 'username=value1&password=passwordValue&token=true' where - gateway is the base URL to the Qualys API server where your account is located. - **username** and **password** are the credentials of the user account for which you want to fetch Container Security data. - **token** should be **true** - **Content-Type** should be **application/x-www-form-urlencoded**   # noqa: E501

    OpenAPI spec version: v1.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AwsConnectorRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'arn': 'str',
        'description': 'str',
        'external_id': 'str',
        'name': 'str'
    }

    attribute_map = {
        'arn': 'arn',
        'description': 'description',
        'external_id': 'externalId',
        'name': 'name'
    }

    def __init__(self, arn=None, description=None, external_id=None, name=None):  # noqa: E501
        """AwsConnectorRequest - a model defined in Swagger"""  # noqa: E501
        self._arn = None
        self._description = None
        self._external_id = None
        self._name = None
        self.discriminator = None
        if arn is not None:
            self.arn = arn
        if description is not None:
            self.description = description
        if external_id is not None:
            self.external_id = external_id
        if name is not None:
            self.name = name

    @property
    def arn(self):
        """Gets the arn of this AwsConnectorRequest.  # noqa: E501


        :return: The arn of this AwsConnectorRequest.  # noqa: E501
        :rtype: str
        """
        return self._arn

    @arn.setter
    def arn(self, arn):
        """Sets the arn of this AwsConnectorRequest.


        :param arn: The arn of this AwsConnectorRequest.  # noqa: E501
        :type: str
        """

        self._arn = arn

    @property
    def description(self):
        """Gets the description of this AwsConnectorRequest.  # noqa: E501


        :return: The description of this AwsConnectorRequest.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this AwsConnectorRequest.


        :param description: The description of this AwsConnectorRequest.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def external_id(self):
        """Gets the external_id of this AwsConnectorRequest.  # noqa: E501


        :return: The external_id of this AwsConnectorRequest.  # noqa: E501
        :rtype: str
        """
        return self._external_id

    @external_id.setter
    def external_id(self, external_id):
        """Sets the external_id of this AwsConnectorRequest.


        :param external_id: The external_id of this AwsConnectorRequest.  # noqa: E501
        :type: str
        """

        self._external_id = external_id

    @property
    def name(self):
        """Gets the name of this AwsConnectorRequest.  # noqa: E501


        :return: The name of this AwsConnectorRequest.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this AwsConnectorRequest.


        :param name: The name of this AwsConnectorRequest.  # noqa: E501
        :type: str
        """

        self._name = name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AwsConnectorRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AwsConnectorRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
