# coding: utf-8

"""
    Container Security API

    # Authentication You must authenticate to the Qualys Cloud Platform using Qualys account credentials (user name and password) and get the JSON Web Token (JWT) before you can start using the Container Security APIs. Use the Qualys Authentication API to get the JWT.  **Example Authentication Curl Request**:  curl -X POST https://gateway/auth -H 'Content-Type: application/x-www-form-urlencoded' -d 'username=value1&password=passwordValue&token=true' where - gateway is the base URL to the Qualys API server where your account is located. - **username** and **password** are the credentials of the user account for which you want to fetch Container Security data. - **token** should be **true** - **Content-Type** should be **application/x-www-form-urlencoded**   # noqa: E501

    OpenAPI spec version: v1.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ClusterK8s(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'project': 'str',
        'pod': 'ClusterK8sPod',
        'node': 'ClusterK8sNode'
    }

    attribute_map = {
        'project': 'project',
        'pod': 'pod',
        'node': 'node'
    }

    def __init__(self, project=None, pod=None, node=None):  # noqa: E501
        """ClusterK8s - a model defined in Swagger"""  # noqa: E501
        self._project = None
        self._pod = None
        self._node = None
        self.discriminator = None
        if project is not None:
            self.project = project
        if pod is not None:
            self.pod = pod
        if node is not None:
            self.node = node

    @property
    def project(self):
        """Gets the project of this ClusterK8s.  # noqa: E501


        :return: The project of this ClusterK8s.  # noqa: E501
        :rtype: str
        """
        return self._project

    @project.setter
    def project(self, project):
        """Sets the project of this ClusterK8s.


        :param project: The project of this ClusterK8s.  # noqa: E501
        :type: str
        """

        self._project = project

    @property
    def pod(self):
        """Gets the pod of this ClusterK8s.  # noqa: E501


        :return: The pod of this ClusterK8s.  # noqa: E501
        :rtype: ClusterK8sPod
        """
        return self._pod

    @pod.setter
    def pod(self, pod):
        """Sets the pod of this ClusterK8s.


        :param pod: The pod of this ClusterK8s.  # noqa: E501
        :type: ClusterK8sPod
        """

        self._pod = pod

    @property
    def node(self):
        """Gets the node of this ClusterK8s.  # noqa: E501


        :return: The node of this ClusterK8s.  # noqa: E501
        :rtype: ClusterK8sNode
        """
        return self._node

    @node.setter
    def node(self, node):
        """Sets the node of this ClusterK8s.


        :param node: The node of this ClusterK8s.  # noqa: E501
        :type: ClusterK8sNode
        """

        self._node = node

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ClusterK8s, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ClusterK8s):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
