# coding: utf-8

"""
    Container Security API

    # Authentication You must authenticate to the Qualys Cloud Platform using Qualys account credentials (user name and password) and get the JSON Web Token (JWT) before you can start using the Container Security APIs. Use the Qualys Authentication API to get the JWT.  **Example Authentication Curl Request**:  curl -X POST https://gateway/auth -H 'Content-Type: application/x-www-form-urlencoded' -d 'username=value1&password=passwordValue&token=true' where - gateway is the base URL to the Qualys API server where your account is located. - **username** and **password** are the credentials of the user account for which you want to fetch Container Security data. - **token** should be **true** - **Content-Type** should be **application/x-www-form-urlencoded**   # noqa: E501

    OpenAPI spec version: v1.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ImageAssociation(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'containers': 'list[Container]',
        'drift_containers': 'list[Container]',
        'hosts': 'list[ImageAssociationHosts]'
    }

    attribute_map = {
        'containers': 'containers',
        'drift_containers': 'driftContainers',
        'hosts': 'hosts'
    }

    def __init__(self, containers=None, drift_containers=None, hosts=None):  # noqa: E501
        """ImageAssociation - a model defined in Swagger"""  # noqa: E501
        self._containers = None
        self._drift_containers = None
        self._hosts = None
        self.discriminator = None
        if containers is not None:
            self.containers = containers
        if drift_containers is not None:
            self.drift_containers = drift_containers
        if hosts is not None:
            self.hosts = hosts

    @property
    def containers(self):
        """Gets the containers of this ImageAssociation.  # noqa: E501


        :return: The containers of this ImageAssociation.  # noqa: E501
        :rtype: list[Container]
        """
        return self._containers

    @containers.setter
    def containers(self, containers):
        """Sets the containers of this ImageAssociation.


        :param containers: The containers of this ImageAssociation.  # noqa: E501
        :type: list[Container]
        """

        self._containers = containers

    @property
    def drift_containers(self):
        """Gets the drift_containers of this ImageAssociation.  # noqa: E501


        :return: The drift_containers of this ImageAssociation.  # noqa: E501
        :rtype: list[Container]
        """
        return self._drift_containers

    @drift_containers.setter
    def drift_containers(self, drift_containers):
        """Sets the drift_containers of this ImageAssociation.


        :param drift_containers: The drift_containers of this ImageAssociation.  # noqa: E501
        :type: list[Container]
        """

        self._drift_containers = drift_containers

    @property
    def hosts(self):
        """Gets the hosts of this ImageAssociation.  # noqa: E501


        :return: The hosts of this ImageAssociation.  # noqa: E501
        :rtype: list[ImageAssociationHosts]
        """
        return self._hosts

    @hosts.setter
    def hosts(self, hosts):
        """Sets the hosts of this ImageAssociation.


        :param hosts: The hosts of this ImageAssociation.  # noqa: E501
        :type: list[ImageAssociationHosts]
        """

        self._hosts = hosts

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ImageAssociation, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ImageAssociation):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
