# coding: utf-8

"""
    Container Security API

    # Authentication You must authenticate to the Qualys Cloud Platform using Qualys account credentials (user name and password) and get the JSON Web Token (JWT) before you can start using the Container Security APIs. Use the Qualys Authentication API to get the JWT.  **Example Authentication Curl Request**:  curl -X POST https://gateway/auth -H 'Content-Type: application/x-www-form-urlencoded' -d 'username=value1&password=passwordValue&token=true' where - gateway is the base URL to the Qualys API server where your account is located. - **username** and **password** are the credentials of the user account for which you want to fetch Container Security data. - **token** should be **true** - **Content-Type** should be **application/x-www-form-urlencoded**   # noqa: E501

    OpenAPI spec version: v1.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from swagger_client.api_client import ApiClient


class SensorApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def delete_cs_sensors(self, **kwargs):  # noqa: E501
        """Delete sensors in your account  # noqa: E501

        Provide one or more sensor Ids or filters in the format shown under Example Value  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_cs_sensors(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param list[str] sensor_ids: delete the sensors from uuid
        :param str filter: delete the sensors from filter
        :return: str
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.delete_cs_sensors_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.delete_cs_sensors_with_http_info(**kwargs)  # noqa: E501
            return data

    def delete_cs_sensors_with_http_info(self, **kwargs):  # noqa: E501
        """Delete sensors in your account  # noqa: E501

        Provide one or more sensor Ids or filters in the format shown under Example Value  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_cs_sensors_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param list[str] sensor_ids: delete the sensors from uuid
        :param str filter: delete the sensors from filter
        :return: str
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['sensor_ids', 'filter']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method delete_cs_sensors" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'sensor_ids' in params:
            query_params.append(('sensorIds', params['sensor_ids']))  # noqa: E501
            collection_formats['sensorIds'] = 'multi'  # noqa: E501
        if 'filter' in params:
            query_params.append(('filter', params['filter']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['bearerAuth']  # noqa: E501

        return self.api_client.call_api(
            '/sensors', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='str',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_cs_sensor_details(self, sensor_id, **kwargs):  # noqa: E501
        """Show details of a sensor  # noqa: E501

        Show details of a sensor  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_cs_sensor_details(sensor_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str sensor_id: Specify the sensor ID of a specific sensor in the user’s scope (required)
        :return: Sensor
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_cs_sensor_details_with_http_info(sensor_id, **kwargs)  # noqa: E501
        else:
            (data) = self.get_cs_sensor_details_with_http_info(sensor_id, **kwargs)  # noqa: E501
            return data

    def get_cs_sensor_details_with_http_info(self, sensor_id, **kwargs):  # noqa: E501
        """Show details of a sensor  # noqa: E501

        Show details of a sensor  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_cs_sensor_details_with_http_info(sensor_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str sensor_id: Specify the sensor ID of a specific sensor in the user’s scope (required)
        :return: Sensor
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['sensor_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_cs_sensor_details" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'sensor_id' is set
        if ('sensor_id' not in params or
                params['sensor_id'] is None):
            raise ValueError("Missing the required parameter `sensor_id` when calling `get_cs_sensor_details`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'sensor_id' in params:
            path_params['sensorId'] = params['sensor_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['bearerAuth']  # noqa: E501

        return self.api_client.call_api(
            '/sensors/{sensorId}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Sensor',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_cs_sensors_list(self, **kwargs):  # noqa: E501
        """Show a list of sensors in your account.  # noqa: E501

        Show a list of sensors in your account.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_cs_sensors_list(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str filter: Filter the sensors list by providing a query using Qualys syntax.
        :param int page_number: The page to be returned.
        :param int page_size: The number of records per page to be included in the response.
        :param str sort: Sort the results using a Qualys token.
        :return: Sensors
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_cs_sensors_list_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.get_cs_sensors_list_with_http_info(**kwargs)  # noqa: E501
            return data

    def get_cs_sensors_list_with_http_info(self, **kwargs):  # noqa: E501
        """Show a list of sensors in your account.  # noqa: E501

        Show a list of sensors in your account.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_cs_sensors_list_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str filter: Filter the sensors list by providing a query using Qualys syntax.
        :param int page_number: The page to be returned.
        :param int page_size: The number of records per page to be included in the response.
        :param str sort: Sort the results using a Qualys token.
        :return: Sensors
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['filter', 'page_number', 'page_size', 'sort']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_cs_sensors_list" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'filter' in params:
            query_params.append(('filter', params['filter']))  # noqa: E501
        if 'page_number' in params:
            query_params.append(('pageNumber', params['page_number']))  # noqa: E501
        if 'page_size' in params:
            query_params.append(('pageSize', params['page_size']))  # noqa: E501
        if 'sort' in params:
            query_params.append(('sort', params['sort']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['bearerAuth']  # noqa: E501

        return self.api_client.call_api(
            '/sensors', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Sensors',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
